### ISSUE TITLE
Add a default-path when creating excalidraw

### ISSUE THREAD

**Issue by nowislewis** [4honor/org-excalidraw#1]
Thanks for your work! I would like to suggest adding a default-path option when creating excalidraw files.

Currently, it defaults to the working directory, which makes it easy to mix org files and excalidraw. By allowing a specific path for excalidraw, users could store all their excalidraw files in one directory in a rather easy way, such as:
``` elisp
(defun org-excalidraw-create-drawing ()
  "Create an excalidraw drawing and insert an org-mode link at point."
  (interactive)
  (let* ((path (read-file-name "Enter path: " default-directory))
         (link (format "[[excalidraw:%s]]" path)))
    (if (not (file-exists-p path))
        (with-temp-file path
          (insert org-excalidraw-default-template)))
    (insert link)
    (org-excalidraw-link-open path)))

```

**Comment by 4honor** [comment]
I've added a new customization variable `org-excalidraw-default-directory`, please check if it's what you expected : )
